<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.Chain</code>
 */
class Chain extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; The blockchain the node is on (eg bitcoin, litecoin)
     *
     * Generated from protobuf field <code>string chain = 1[json_name = "chain"];</code>
     */
    private $chain = '';
    /**
     *&#47; The network the node is on (eg regtest, testnet, mainnet)
     *
     * Generated from protobuf field <code>string network = 2[json_name = "network"];</code>
     */
    private $network = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     *&#47; The blockchain the node is on (eg bitcoin, litecoin)
     *
     * Generated from protobuf field <code>string chain = 1[json_name = "chain"];</code>
     * @return string
     */
    public function getChain()
    {
        return $this->chain;
    }

    /**
     *&#47; The blockchain the node is on (eg bitcoin, litecoin)
     *
     * Generated from protobuf field <code>string chain = 1[json_name = "chain"];</code>
     * @param string $var
     * @return $this
     */
    public function setChain($var)
    {
        GPBUtil::checkString($var, True);
        $this->chain = $var;

        return $this;
    }

    /**
     *&#47; The network the node is on (eg regtest, testnet, mainnet)
     *
     * Generated from protobuf field <code>string network = 2[json_name = "network"];</code>
     * @return string
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     *&#47; The network the node is on (eg regtest, testnet, mainnet)
     *
     * Generated from protobuf field <code>string network = 2[json_name = "network"];</code>
     * @param string $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkString($var, True);
        $this->network = $var;

        return $this;
    }

}

