<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

/**
 * Protobuf enum <code>Lnrpc\ChannelCloseSummary\ClosureType</code>
 */
class ChannelCloseSummary_ClosureType
{
    /**
     * Generated from protobuf enum <code>COOPERATIVE_CLOSE = 0;</code>
     */
    const COOPERATIVE_CLOSE = 0;
    /**
     * Generated from protobuf enum <code>LOCAL_FORCE_CLOSE = 1;</code>
     */
    const LOCAL_FORCE_CLOSE = 1;
    /**
     * Generated from protobuf enum <code>REMOTE_FORCE_CLOSE = 2;</code>
     */
    const REMOTE_FORCE_CLOSE = 2;
    /**
     * Generated from protobuf enum <code>BREACH_CLOSE = 3;</code>
     */
    const BREACH_CLOSE = 3;
    /**
     * Generated from protobuf enum <code>FUNDING_CANCELED = 4;</code>
     */
    const FUNDING_CANCELED = 4;
    /**
     * Generated from protobuf enum <code>ABANDONED = 5;</code>
     */
    const ABANDONED = 5;
}

