<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lnrpc.ChannelBackups</code>
 */
class ChannelBackups extends \Google\Protobuf\Internal\Message
{
    /**
     **
     *A set of single-chan static channel backups.
     *
     * Generated from protobuf field <code>repeated .lnrpc.ChannelBackup chan_backups = 1[json_name = "chan_backups"];</code>
     */
    private $chan_backups;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     **
     *A set of single-chan static channel backups.
     *
     * Generated from protobuf field <code>repeated .lnrpc.ChannelBackup chan_backups = 1[json_name = "chan_backups"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChanBackups()
    {
        return $this->chan_backups;
    }

    /**
     **
     *A set of single-chan static channel backups.
     *
     * Generated from protobuf field <code>repeated .lnrpc.ChannelBackup chan_backups = 1[json_name = "chan_backups"];</code>
     * @param \Lnrpc\ChannelBackup[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChanBackups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lnrpc\ChannelBackup::class);
        $this->chan_backups = $arr;

        return $this;
    }

}

