<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

/**
 * Protobuf enum <code>Lnrpc\ChannelEventUpdate\UpdateType</code>
 */
class ChannelEventUpdate_UpdateType
{
    /**
     * Generated from protobuf enum <code>OPEN_CHANNEL = 0;</code>
     */
    const OPEN_CHANNEL = 0;
    /**
     * Generated from protobuf enum <code>CLOSED_CHANNEL = 1;</code>
     */
    const CLOSED_CHANNEL = 1;
    /**
     * Generated from protobuf enum <code>ACTIVE_CHANNEL = 2;</code>
     */
    const ACTIVE_CHANNEL = 2;
    /**
     * Generated from protobuf enum <code>INACTIVE_CHANNEL = 3;</code>
     */
    const INACTIVE_CHANNEL = 3;
}

