<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lnd.proto

namespace Lnrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>lnrpc.DebugLevelResponse</code>
 */
class DebugLevelResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sub_systems = 1[json_name = "sub_systems"];</code>
     */
    private $sub_systems = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sub_systems
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Lnd::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sub_systems = 1[json_name = "sub_systems"];</code>
     * @return string
     */
    public function getSubSystems()
    {
        return $this->sub_systems;
    }

    /**
     * Generated from protobuf field <code>string sub_systems = 1[json_name = "sub_systems"];</code>
     * @param string $var
     * @return $this
     */
    public function setSubSystems($var)
    {
        GPBUtil::checkString($var, True);
        $this->sub_systems = $var;

        return $this;
    }

}

