<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

/**
 * Protobuf enum <code>Lnrpc\InvoiceHTLCState</code>
 */
class InvoiceHTLCState
{
    /**
     * Generated from protobuf enum <code>ACCEPTED = 0;</code>
     */
    const ACCEPTED = 0;
    /**
     * Generated from protobuf enum <code>SETTLED = 1;</code>
     */
    const SETTLED = 1;
    /**
     * Generated from protobuf enum <code>CANCELED = 2;</code>
     */
    const CANCELED = 2;
}

