<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Lnrpc;

/**
 * Protobuf enum <code>Lnrpc\Payment\PaymentStatus</code>
 */
class Payment_PaymentStatus
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>IN_FLIGHT = 1;</code>
     */
    const IN_FLIGHT = 1;
    /**
     * Generated from protobuf enum <code>SUCCEEDED = 2;</code>
     */
    const SUCCEEDED = 2;
    /**
     * Generated from protobuf enum <code>FAILED = 3;</code>
     */
    const FAILED = 3;
}

